config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get 'search' => 'users#search', :as => 'search_page'
  resources :users, only: [:show] do member do
  	patch 'follow'
  	patch 'unfollow'
  end
end

  resources :posts do member do
  	patch 'like_posts'
  	patch 'dislike_posts'
  end
  	resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment_post.rb
class AttachmentPost < ApplicationRecord
	mount_uploader :foto, FotoUploader
	belongs_to :post
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
	belongs_to  :parent, class_name: 'Comment', optional: true
  	has_many    :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
  	
	belongs_to :user
end

app/models/following.rb
class Following < ApplicationRecord
	belongs_to :user

	# def followed?
 #      follow = Followed.find_by(user_id: self.id)
 #    end 
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :attachment_posts
    accepts_nested_attributes_for :attachment_posts
	has_many :likes
	has_many :comments

	default_scope { order(created_at: :desc) }

	# def liked_by_user(user)
	# 	Like.find_by(user: user)&.user_id || User.find_by(id: user)
	# end
	def liked_by_user?
		Like.where(user_id: current_user.id, post_id:
	  	params[:post_id]).exists?
	end

	scope :show_post, -> { where user_id: Following.user_id }

end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   validates_uniqueness_of :name, case_sensitive: false
   validates_presence_of :name

   validates_uniqueness_of :email, case_sensitive: false
   validates_presence_of :email

	has_many :posts
	has_many :comments
	has_many :likes
	has_many :followings

  scope :filter_by_starts_with, -> (name) { where("name like ?", "#{name}%")}
  def liked_by_user?
    Following.where(user_id: current_user.id, post_id:
      params[:post_id]).exists?
  end

  def following?(user)
    followings.find_by(follower_id: user.id)
  end

  def feed
    following_ids = "SELECT follower_id FROM followings
                     WHERE  user_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)   
  end

  before_save { self.name.downcase!}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
	    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :name, :password_confirmation, :remember_me, :avatar, :avatar_cache) }
	    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :password, :name, :password_confirmation, :current_password, :avatar, :avatar_cache, :remove_avatar) }
	  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	   def new
	   	@post = Post.find(params[:post_id])
    	@comment = @post.comments.new(parent_id: params[:parent_id])

	   end

	   def create
	    @post = Post.find(params[:post_id])
		@comment = Comment.new(comment_params)

		@comment.post_id = @post.id
		@comment.user_id = current_user.id

		respond_to do |format|
	      if @comment.save
	        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
	        format.json { render :show, status: :created, location: @comment }
	      else
	        format.html { render :new }
	        format.json { render json: @comment.errors, status: :unprocessable_entity }
	      end
	    end

	  end

    private

    def comment_params
    	params.require(:comment).permit(:comment, :parent_id, :user_id)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	before_action :post_params

	def index
		@post = current_user.feed
		# @posts = Post.where(:user_id => current_user.followings.id)
	end

	def new
		@post = Post.new
		@attachment_post = @post.attachment_posts.build
	end

	def show
		@post = Post.find(params[:id])
		@attachment_posts = @post.attachment_posts.all

		@comment = Comment.new
	end
	
	def create
		content = params[:post][:content]
		@post = current_user.posts.new(content: content)
		if @post.save
			params[:attachment_posts]['foto'].each do |a|
              @attachment_post = @post.attachment_posts.create!(:foto => a, :post_id => @post.id)
          end
              flash[:notice] = "Succes Create Post"
              redirect_to root_path
      	else
      		flash[:notice] = "Fail Create New Post"
      		redirect_to new_post_path
		end
	end

	def destroy
	    @post = Post.find(params[:id])
    	@post.destroy

    	redirect_to root_path
	end

    def like_posts
	  @post = Post.find(params[:id])
      like_posts = @post.likes.find_or_create_by(post_id: @post.id, user: current_user)
      redirect_back fallback_location: root_path(@post.id)
    end

    def dislike_posts
    	q = Post.find(params[:id])
    	w = q.likes
    	e = w.find_by(post_id: params[:id], user_id: current_user.id)
    	if e.user_id == current_user.id
	      a = Post.find(params[:id])
	      b = a.likes
	      c = b.find_by(post_id: params[:id], user_id: current_user.id)
	      d = c.destroy
	      redirect_back fallback_location: root_path(a.id)
    		else
	      redirect_back fallback_location: root_path(a.id)
    	end
    end

	private

	def post_params
		params.permit(attachment_posts_attributes: [:id, :post_id, :foto])
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@user = @user.filter_by_starts_with(params[:name]) if params[:name].present?
	end

	def show
		@user = User.find(params[:id])
	end

	def follow
		@user = User.find(params[:id])
        follow = current_user.followings.create(follower_id: @user.id)
        redirect_back fallback_location: user_path(@user)
	end

	def unfollow
		@user = User.find(params[:id])
		d = current_user.followings.find_by(follower_id: @user.id)
		d.destroy
		redirect_back fallback_location: user_path(@user)
	end

	def search
		if params[:search].blank?  
            redirect_to(root_path, alert: "Empty field!") and return  
        else  
        	@parameter = params[:search].downcase  
    		@results = User.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
        end  
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<% unless comment.parent_id || !comment.persisted? %>
<div class="card">
  <div class="card-body">
     <b><%= comment.post.user.name %></b> <%= comment.comment %><br>
     <%= time_ago_in_words(comment.created_at) %>
     <%= link_to 'reply', new_post_comment_path(@post, parent_id: comment.id), remote: true, class: 'd-block' %>
  </div>
</div>

  <% if comment.replies.any? %>
    <% comment.replies.each do |reply| %> 
      <%= render partial: 'comments/reply', locals: { reply: reply } %>
    <% end %>
  <% end %>
  <div id="reply-form-<%= comment.id %>"></div>
<% end %>

app/views/comments/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
    <b><%= reply.post.user.name %></b> <%= reply.comment %> <br>
     Post at <%= time_ago_in_words(reply.created_at) %> ago
  </div>
</div>

app/views/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_with(model: [@post, @comment], remote: true) do |f| %>
      <%= f.hidden_field :parent_id %>
      <div class="form-group">
        <%= f.label 'Reply' %>
        <%= f.text_area :comment, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', post_path(@post), class: 'btn btn-secondary' %>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<%= render 'reply_form' %>

app/views/layouts/_navbar.html.erb
    <% if user_signed_in? %>
    <div class="wrapper d-flex align-items-stretch">
      <nav id="sidebar">
        <div class="p-4 pt-5">
          <%= image_tag(current_user.avatar.url, size: "400x300", class: 'img logo rounded-circle mb-5')%>
          <ul class="list-unstyled components mb-5">
            <li class="active">
                <div class="counter d-flex justify-content-center">
                  <div class="row justify-content-center">
                    <div class="col">
                      <strong class="number"><%= current_user.posts.count %></strong><br>
                      <span class="number-label">Posts</span>
                    </div>
                    <div class="col">
                      <strong class="number"><%= Following.where(follower_id: current_user.id).count %></strong>
                      <span class="number-label">Followers</span>
                    </div>
                    <div class="col">
                      <strong class="number"><%= current_user.followings.count %></strong>
                      <span class="number-label">Following</span>
                    </div>
                  </div>
              </div>
            </li>
            <li>
              <a href=""><%= link_to "Home", root_path %></a>
            </li>
            <li>
              <a href=""><%= link_to "Create New Post", new_post_path %></a>
            </li>
            <li>
              <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle"><%= current_user.name %></a>
              <ul class="collapse list-unstyled" id="homeSubmenu">
                <li>
                    <a href=""><%= link_to "Profile User", user_path(current_user) %></a>
                </li>
                <li>
                    <a href=""><%= link_to "Edit Profile", edit_user_registration_path %></a>
                </li>
                <li>
                    <a href=""><%= button_to "Logout", destroy_user_session_path, method: :delete %></a>
                </li>
              </ul>
            </li>
          </ul>
          <div class="footer">
            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              NineGram &copy;<script>document.write(new Date().getFullYear());</script>
              <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </nav>
      <% end %>
        <!-- Page Content  -->
        <% if user_signed_in? %>
      <div id="content" class="p-4 p-md-5">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">

            <button type="button" id="sidebarCollapse" class="btn btn-primary">
              <i class="fa fa-bars"></i>
              <span class="sr-only">Toggle Menu</span>
            </button>
            <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="nav navbar-nav">
                <li class="nav-item active" style="padding-left: 15px;">
                    <a class="nav-link" href="<% root_path %>">Home</a>
                </li>
                <%= render 'users/header' %>
              </ul>
            </div>
          </div>
        </nav>
        <% end %>
        <%= yield %>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sosmed</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ujs/1.2.2/rails.min.js" integrity="sha256-DrT5NfxfbHvMHux31Lkhxg42LY6of8TaYyK50jnxRnM=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
  </body>

  <script>
    (function($) {
      "use strict";
      var fullHeight = function() {
        $('.js-fullheight').css('height', $(window).height());
        $(window).resize(function(){
          $('.js-fullheight').css('height', $(window).height());
        });
      };
      fullHeight();
      $('#sidebarCollapse').on('click', function () {
          $('#sidebar').toggleClass('active');
      });
    })(jQuery);

  $(document).on('turbolinks:load', function(){
     $('.carousel').carousel({
        interval: 2000
     });
  });
  </script>
</html>

app/views/posts/_comment.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
  <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
</svg>

app/views/posts/_like.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
  <path d="M8 6.236l-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
</svg>

app/views/posts/_liked.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
  <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
</svg>

app/views/posts/index.html.erb
<div class="container">
	<% @post.each do |p| %>
		<div class="card offset-1" style="width: 60rem;">
			<div class="card-header"><%= image_tag(current_user.avatar.url, size: "60x50", class: 'img logo rounded-circle mb-12')%>&nbsp;&nbsp;&nbsp;<b><%= p.user.name %></b></div>
			   <div id="carouselExampleIndicators" class="carousel slide" data-interval="false">
				  <ol class="carousel-indicators">
				    <% p.attachment_posts.each.with_index(0) do |post, index| %>
				      <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
				    <% end %>
				  </ol>
				  <div class="carousel-inner">
				    <% p.attachment_posts.each.with_index(0) do |post, index| %>
				      <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
				        <%= link_to post.foto.url do %>
				          <%= link_to image_tag(post.foto_url, class: 'd-block w-100 img-fluid'), post_path(p.id) %>
				        <% end %>
				      </div>
				    <% end %>
				  </div>
				  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
				    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
				    <span class="sr-only">Previous</span>
				  </a>
				  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
				    <span class="carousel-control-next-icon" aria-hidden="true"></span>
				    <span class="sr-only">Next</span>
				  </a>
				</div>
			  <div class="card-body">
			  		<div class="row" style="padding-left: 10px;">
			  			<% pre_like = p.likes.find { |like| like.user_id == current_user.id} %>
			  			<% if pre_like %>
				  			<%= button_to dislike_posts_post_path(p.id), method: :patch, style: 'background: none; border: none;', class: 'submit1' do %>
				  				<a href=""><%= render 'liked' %></a>
				  			<% end %>&nbsp;&nbsp;&nbsp;
				  		<% else %>
				  			<%= button_to like_posts_post_path(p.id), method: :patch, style: 'background: none; border: none;', class: 'submit' do %>
				  				<a href=""><%= render 'like' %></a>
				  			<% end %>&nbsp;&nbsp;&nbsp;
				  		<% end %>
			  			
			  			<a href="/posts/<%= p.id %>">
				  			<%= render 'comment' %>
				  		</a>
			  		</div>
			  	<p class="card-text" style="padding-top: 10px; font-size: 15px;"><b>Likes</b> <%= p.likes.count %> </p>
			    <p class="card-text" style="font-size: 20px; font-family: Arial, Helvetica, sans-serif;"><b><%= p.user.name %></b> <%= p.content %></p>
			    <a href="/posts/<%= p.id %>" style="font-size: 15px;"><p class="card-text"> View All <%= p.comments.ids.count %> Comments</p></a>

			    <p>Post at <%= time_ago_in_words(p.updated_at) %> ago<br></p>
			  </div>
		</div><br>
	<% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
	<%= form_with model: @post, url: posts_path, :html => { :multipart => true } do |p| %>

		<div class="form-group">
			<h4><%= p.label :content %></h4>
			<%= p.text_area :content, class: 'form-control col-md-5', rows: 8 %>
		</div>

		<%= p.fields_for :attachment_posts do |f| %>
         <div class="field">
           <%= f.label :Photos %><br>
           <%= f.file_field :foto, :multiple => true, name:"attachment_posts[foto][]" %>
         </div>
       <% end %><br>

       <%= p.submit "Create Post", class: 'btn-md btn-primary' %>

	<% end %>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="card offset-1" style="width: 60rem;">
		<div class="card-header"><b><%= @post.user.name %></b> 
			<button class="btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="float: right;">
			    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-three-dots-vertical" viewBox="0 0 16 16">
				  <path d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
				</svg>
			  </button>
				<% if @user == current_user %>
			<div class="dropdown">
			  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
			    <%= button_to "Delete Post", post_path, class: 'dropdown-item', method: :delete %>
			  </div>
			</div>
			  <% end %>
		</div>
			<div id="carouselExampleIndicators" class="carousel slide" data-interval="false">
			  <ol class="carousel-indicators">
			    <% @post.attachment_posts.each.with_index(0) do |post, index| %>
			      <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="<%= index.zero? ? 'active' : '' %>"></li>
			    <% end %>
			  </ol>
			  <div class="carousel-inner">
			    <% @post.attachment_posts.each.with_index(0) do |post, index| %>
			      <div class="carousel-item <%= index.zero? ? 'active' : '' %>">
			        <%= link_to post.foto.url do %>
			          <%= image_tag(post.foto_url, class: 'd-block w-100 img-fluid') %>
			        <% end %>
			      </div>
			    <% end %>
			  </div>
			  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
			    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
			    <span class="sr-only">Previous</span>
			  </a>
			  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
			    <span class="carousel-control-next-icon" aria-hidden="true"></span>
			    <span class="sr-only">Next</span>
			  </a>
			</div>
			<div class="card-body">
				<div class="row" style="padding-left: 10px;">
		  			<% pre_like = @post.likes.find { |like| like.user_id == current_user.id} %>
		  			<% if pre_like %>
			  			<%= button_to dislike_posts_post_path(@post.id), method: :patch, style: 'background: none; border: none;' do %>
			  				<a href=""><%= render 'liked' %></a>
			  			<% end %>&nbsp;&nbsp;&nbsp;
			  		<% else %>
			  			<%= button_to like_posts_post_path(@post.id), method: :patch, style: 'background: none; border: none;' do %>
			  				<a href=""><%= render 'like' %></a>
			  			<% end %>&nbsp;&nbsp;&nbsp;
			  		<% end %>
		  			
		  			<a href="/posts/<%= @post.id %>">
			  			<%= render 'comment' %>
			  		</a>
		  		</div>
			  	<p class="card-text" style="padding-top: 10px; font-size: 15px;"><b>Likes</b> <%= @post.likes.count %> </p>
			   <p class="card-text"><%= @post.content %></p>
			   Post at <%= time_ago_in_words(@post.created_at) %> ago
			</div>
			  	<%= render @post.comments %>
			  <div class="card my-1">
				  <div class="card-body">
				    <p class="font-weight-bold">Comments</p>
				    <%= form_for [@post, @post.comments.build] do |f| %>
				      <div class="form-group">
				        <%= f.label 'New comment' %>
				        <%= f.text_area :comment, class: 'form-control' %>
				      </div>
				      <div class="form-group">
				        <%= f.submit 'Submit', class: 'btn btn-primary' %>
				      </div>
				    <% end %>
				  </div>
				</div>

	</div>
</div>

app/views/users/_header.html.erb
<%= form_tag(search_page_path, :method => "get",   
    class: 'navbar-form navbar-left') do %>  
  <div class="input-group">  
    <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
    <div class="input-group-btn">  
      <%= button_tag "Search", :class => 'btn btn-info glyphicon glyphicon-search',:name => nil%>  
    </div>  
  </div>  
<% end %>

app/views/users/search.html.erb
<% @results.each do |result| %>  
        <div class="container">
        	<ul>
        		<li><a href="<%= user_path(result) %>" style="color: black; font-size: 25px;"><% result.id %> <%= result.name %><br></a></li>
        	</ul>
        </div>  
<% end %>

app/views/users/show.html.erb
	<div class="row">
		<div class="col-4"><%= image_tag(@user.avatar.url, size: "300x250", class: 'img logo rounded-circle mb-5')%></div>
			<div class="col-8" style="padding-left: 50px;"><br><br>
				<div class="row">
					<a style="font-size: 20px;"><b style="padding-left: 15px;"><%= @user.name %></b></a>
					<% unless @user.id == current_user.id %>
					<% if current_user.following?(@user)%>
						<a style="padding-left: 20px;"><%= button_to "Unfollow", unfollow_user_path(@user), method: :patch, class: 'btn btn-primary', style: 'font-size: 15px;' %></a>
					<% else %>
						<a style="padding-left: 20px;"><%= button_to "Follow", follow_user_path(@user), method: :patch,class: 'btn btn-primary', style: 'font-size: 15px;'%></a>
					<% end %>
					<% end %>
				</div><br>
	                <div class="counter d-flex">
	                  <div class="row">
	                    <div class="col">
	                      <strong class="number"><%= @user.posts.count %> Posts</strong>
	                    </div>
	                    <div class="">
	                      <strong class="number" ><%= Following.where(follower_id: @user.id).count %> Followers</strong>
	                    </div>
	                    <div class="">
	                      <strong class="number" style="padding-left: 20px;"><%= @user.followings.count %> Following</strong>
	                    </div>
	              	  </div>
					</div>

			</div>
		</div><br>
		<hr noshade size="30%">
		<h4>Postingan: <%= @user.name %></h4>
		<div class="row">
			<% @user.posts.each do |p| %>
				<% p.attachment_posts.each do |foto, index| %>
				  <div class="col-md">
			        <%= link_to foto.foto.url do %>
				  	  <%= link_to image_tag(foto.foto_url, size: "300x300"), post_path(p.id) %> <br><br>
			        <% end %>
				  </div>
			    <% end %>
			<% end %>
		</div>